# Pandas Reshape Tutorial

Using: [link](https://www.w3resource.com/pandas/reshaping.php)

In [2]:
import numpy as np
import pandas as pd

In [5]:
tuples = list(zip(*[['green', 'green', 'blue', 'blue', 'red', 'red'],
                    ['one'  , 'two'  , 'one' , 'two' , 'one', 'two']]))


index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame(np.random.randn(6, 2), index=index, columns=['M', 'N'])
df_orig  = df.copy()

df

                     M         N
first second
green one    -0.389523  0.288309
      two    -0.959749 -0.845155
blue  one    -0.856058  0.859695
      two    -0.247632  1.840807
red   one    -0.847284  0.917423
      two    -0.046876  0.203455

In [9]:
# stack
df_stacked = df.stack()
df_stacked

first  second
green  one     M   -0.389523
               N    0.288309
       two     M   -0.959749
               N   -0.845155
blue   one     M   -0.856058
               N    0.859695
       two     M   -0.247632
               N    1.840807
red    one     M   -0.847284
               N    0.917423
       two     M   -0.046876
               N    0.203455
dtype: float64

In [15]:
df_stacked.unstack([0])

first         blue     green       red
second
one    M -0.856058 -0.389523 -0.847284
       N  0.859695  0.288309  0.917423
two    M -0.247632 -0.959749 -0.046876
       N  1.840807 -0.845155  0.203455

### Pivot Tables

In [17]:
# pivot tables

df = pd.DataFrame({'M': ['one', 'one', 'two', 'three'] * 2,
                   'N': ['A', 'B'] * 4,
                   'O': ['blue', 'blue', 'red', 'red'] * 2,
                   'P': np.random.randn(8),
                   'Q': np.random.randn(8)})

df

       M  N     O         P         Q
0    one  A  blue  0.267941 -1.186192
1    one  B  blue  0.458343  0.906010
2    two  A   red  0.049572 -0.504828
3  three  B   red  0.014582  0.298512
4    one  A  blue  0.694409  0.698660
5    one  B  blue  0.211196  1.313326
6    two  A   red -1.739478 -0.357738
7  three  B   red -0.259352  0.771184

In [21]:
pd.pivot_table(df,index=['O','N'],columns=['M'])

               P                             Q
M            one     three       two       one     three       two
O    N
blue A  0.481175       NaN       NaN -0.243766       NaN       NaN
     B  0.334769       NaN       NaN  1.109668       NaN       NaN
red  A       NaN       NaN -0.844953       NaN       NaN -0.431283
     B       NaN -0.122385       NaN       NaN  0.534848       NaN